openapi: 3.1.0
info:
  title: Salesforce Bulk API 2.0 Abort Payments API
  description: 'Salesforce Bulk API 2.0 is a simplified, REST-based interface for bulk data operations that improves on the original Bulk API. It uses a straightforward job model and supports CSV format for ingest and query jobs, enabling processing of millions of records asynchronously.

    '
  version: v63.0
  contact:
    name: Salesforce Developers
    url: https://developer.salesforce.com/
  license:
    name: Salesforce Developer Terms
    url: https://www.salesforce.com/company/legal/agreements/
servers:
- url: https://{instance}.salesforce.com/services/data/v{version}/jobs
  description: Salesforce Bulk API 2.0 jobs endpoint
  variables:
    instance:
      default: yourInstance
      description: 'The Salesforce instance identifier (e.g., na1, eu3, or a My Domain subdomain like mycompany).

        '
    version:
      default: '63.0'
      description: 'The Salesforce API version number (e.g., 63.0). Use the latest supported version for new integrations.

        '
security:
- BearerAuth: []
tags:
- name: Payments
paths:
  /data/v64.0/connect/fundraising/transactions/payment-updates:
    parameters: []
    post:
      tags:
      - Payments
      summary: Salesforce Update Gift Transaction Payments
      description: "Update the gateway and processor metadata for gift transactions.\n\n## Required Attributes:\n\n- giftTransactionId\n    \n- transactionStatus"
      operationId: UpdateGiftTransactionPayments
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateGiftTransactionPaymentsRequest'
              - examples:
                - updates:
                  - giftTransactionId: <SFDC_GIFT_TRANSACTION_ID>
                    transactionStatus: Paid
                    processorReference: string
                    gatewayReference: string
                    lastGatewayResponseCode: invalid_cvc
                    lastGatewayErrorMessage: The card’s security code is invalid. Check the card’s security code or use a different card.
                    lastGatewayProcessedDateTime: '2023-07-06T21:57:51.000Z'
                    processorTransactionFee: 0.5
                    gatewayTransactionFee: 0.25
                    donorCoverAmount: 10.5
                  - giftTransactionId: <SFDC_GIFT_TRANSACTION_ID>
                    transactionStatus: Paid
                    processorReference: string
                    gatewayReference: string
                    lastGatewayResponseCode: invalid_cvc
                    lastGatewayErrorMessage: The card’s security code is invalid. Check the card’s security code or use a different card.
                    lastGatewayProcessedDateTime: '2023-07-06T21:57:51.000Z'
                    processorTransactionFee: 1
                    gatewayTransactionFee: 0.45
                    donorCoverAmount: 20
              contentMediaType: application/json
            example:
              updates:
              - giftTransactionId: <SFDC_GIFT_TRANSACTION_ID>
                transactionStatus: Paid
                processorReference: string
                gatewayReference: string
                lastGatewayResponseCode: invalid_cvc
                lastGatewayErrorMessage: The card’s security code is invalid. Check the card’s security code or use a different card.
                lastGatewayProcessedDateTime: '2023-07-06T21:57:51.000Z'
                processorTransactionFee: 0.5
                gatewayTransactionFee: 0.25
                donorCoverAmount: 10.5
              - giftTransactionId: <SFDC_GIFT_TRANSACTION_ID>
                transactionStatus: Paid
                processorReference: string
                gatewayReference: string
                lastGatewayResponseCode: invalid_cvc
                lastGatewayErrorMessage: The card’s security code is invalid. Check the card’s security code or use a different card.
                lastGatewayProcessedDateTime: '2023-07-06T21:57:51.000Z'
                processorTransactionFee: 1
                gatewayTransactionFee: 0.45
                donorCoverAmount: 20
        required: true
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/Status201-UpdateTransactionPaymentSuccess'
                - examples:
                  - successes: 2
                    failures: 0
                    notProcessed: 0
                    details:
                    - success: true
                      links:
                        gifttransaction:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
                          id: <SFDC_GIFT_TRANSACTION_ID>
                    - success: true
                      links:
                        gifttransaction:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
                          id: <SFDC_GIFT_TRANSACTION_ID>
                contentMediaType: application/json
              example:
                successes: 2
                failures: 0
                notProcessed: 0
                details:
                - success: true
                  links:
                    gifttransaction:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
                      id: <SFDC_GIFT_TRANSACTION_ID>
                - success: true
                  links:
                    gifttransaction:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
                      id: <SFDC_GIFT_TRANSACTION_ID>
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/Status201-UpdateTransactionPaymentWithExternalIds1'
                - examples:
                  - successes: 1
                    failures: 0
                    notProcessed: 0
                    details:
                    - success: true
                      links:
                        gifttransaction:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
                          id: <SFDC_GIFT_TRANSACTION_ID>
                contentMediaType: application/json
              example:
                successes: 1
                failures: 0
                notProcessed: 0
                details:
                - success: true
                  links:
                    gifttransaction:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
                      id: <SFDC_GIFT_TRANSACTION_ID>
      deprecated: false
      servers:
      - url: https://services
        variables: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /data/v64.0/connect/fundraising/commitments/payment-updates:
    parameters: []
    post:
      tags:
      - Payments
      summary: Salesforce Update Commitment Payments
      description: "Update the future payment instrument metadata for active gift commitments.\n\n## Required Attributes:\n\n- giftCommitmentId\n    \n- paymentInstrument.type"
      operationId: UpdateCommitmentPayments
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateCommitmentPaymentsRequest'
              - examples:
                - updates:
                  - giftCommitmentId: <SFDC_GIFT_COMMITMENT_ID>
                    paymentInstrument:
                      type: credit card
                      accountHolderName: test donor 1
                      expiryMonth: '10'
                      expiryYear: '2026'
                      last4: '4585'
                      cardBrand: visa
                      bankName: chase
                      digitalWalletProvider: apple pay
                      bankAccountHolderType: primary
                      bankAccountType: checking
                      bankAccountNumber: '123456'
                      bankCode: HBUK
                      gatewayName: stripe
                      processorName: classy
                      processorPaymentReference: string
                      gatewayReference: string
                  - giftCommitmentId: <SFDC_GIFT_COMMITMENT_ID>
                    paymentInstrument:
                      type: credit card
                      accountHolderName: test donor 2
                      expiryMonth: '10'
                      expiryYear: '2026'
                      last4: '4585'
                      cardBrand: visa
                      bankName: chase
                      digitalWalletProvider: apple pay
                      bankAccountHolderType: primary
                      bankAccountType: checking
                      bankAccountNumber: '123456'
                      bankCode: HBUK
                      gatewayName: stripe
                      processorName: test processor
                      processorPaymentReference: string
                      gatewayReference: string
              contentMediaType: application/json
            example:
              updates:
              - giftCommitmentId: <SFDC_GIFT_COMMITMENT_ID>
                paymentInstrument:
                  type: credit card
                  accountHolderName: test donor 1
                  expiryMonth: '10'
                  expiryYear: '2026'
                  last4: '4585'
                  cardBrand: visa
                  bankName: chase
                  digitalWalletProvider: apple pay
                  bankAccountHolderType: primary
                  bankAccountType: checking
                  bankAccountNumber: '123456'
                  bankCode: HBUK
                  gatewayName: stripe
                  processorName: classy
                  processorPaymentReference: string
                  gatewayReference: string
              - giftCommitmentId: <SFDC_GIFT_COMMITMENT_ID>
                paymentInstrument:
                  type: credit card
                  accountHolderName: test donor 2
                  expiryMonth: '10'
                  expiryYear: '2026'
                  last4: '4585'
                  cardBrand: visa
                  bankName: chase
                  digitalWalletProvider: apple pay
                  bankAccountHolderType: primary
                  bankAccountType: checking
                  bankAccountNumber: '123456'
                  bankCode: HBUK
                  gatewayName: stripe
                  processorName: test processor
                  processorPaymentReference: string
                  gatewayReference: string
        required: true
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/Status201-UpdateCommitmentSuccess'
                - examples:
                  - successes: 2
                    failures: 0
                    notProcessed: 0
                    details:
                    - success: true
                      links:
                        giftcommitment:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
                          id: <SFDC_GIFT_COMMITMENT_ID>
                        paymentinstrument:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
                          id: <SFDC_PAYMENT_INSTRUMENT_ID>
                    - success: true
                      links:
                        giftcommitment:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
                          id: <SFDC_GIFT_COMMITMENT_ID>
                        paymentinstrument:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
                          id: <SFDC_PAYMENT_INSTRUMENT_ID>
                contentMediaType: application/json
              example:
                successes: 2
                failures: 0
                notProcessed: 0
                details:
                - success: true
                  links:
                    giftcommitment:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
                      id: <SFDC_GIFT_COMMITMENT_ID>
                    paymentinstrument:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
                      id: <SFDC_PAYMENT_INSTRUMENT_ID>
                - success: true
                  links:
                    giftcommitment:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
                      id: <SFDC_GIFT_COMMITMENT_ID>
                    paymentinstrument:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
                      id: <SFDC_PAYMENT_INSTRUMENT_ID>
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/Status200-UpdateCommitmentRequestValidationFailure1'
                - examples:
                  - successes: 1
                    failures: 1
                    notProcessed: 0
                    details:
                    - success: false
                      errors:
                        field: id
                        message: <invalid id message>
                    - success: true
                      links:
                        giftcommitment:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
                          id: <SFDC_GIFT_COMMITMENT_ID>
                        paymentinstrument:
                          href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
                          id: <SFDC_PAYMENT_INSTRUMENT_ID>
                contentMediaType: application/json
              example:
                successes: 1
                failures: 1
                notProcessed: 0
                details:
                - success: false
                  errors:
                    field: id
                    message: <invalid id message>
                - success: true
                  links:
                    giftcommitment:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
                      id: <SFDC_GIFT_COMMITMENT_ID>
                    paymentinstrument:
                      href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
                      id: <SFDC_PAYMENT_INSTRUMENT_ID>
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                type: string
                examples:
                - "    // Even if the JSON request is valid, this is an example of a 400 error code that will be returned if duplicate matching rules are not active. Any non 200 error code would have a similar response structure.\n    {\n        \"errorCode\": \"UNKNOWN_EXCEPTION\",\n        \"message\": \"Provide active duplicate matching rules on Account and Person Account for donor matching. -- industries.fundraisingops.connect.impl.validator.ValidatorUtil.validateMatchingMethod(ValidatorUtil.java:103)\"\n    }"
                contentMediaType: application/json
              example: "    // Even if the JSON request is valid, this is an example of a 400 error code that will be returned if duplicate matching rules are not active. Any non 200 error code would have a similar response structure.\n    {\n        \"errorCode\": \"UNKNOWN_EXCEPTION\",\n        \"message\": \"Provide active duplicate matching rules on Account and Person Account for donor matching. -- industries.fundraisingops.connect.impl.validator.ValidatorUtil.validateMatchingMethod(ValidatorUtil.java:103)\"\n    }"
      deprecated: false
      servers:
      - url: https://services
        variables: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /data/v64.0/commerce/payments/payment-methods:
    parameters: []
    post:
      tags:
      - Payments
      summary: Salesforce Create Payment Method
      operationId: CreatePaymentMethod
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreatePaymentMethodRequest'
              - examples:
                - paymentGatewayId: '{{defaultPaymentGatewayId}}'
                  cardPaymentMethod:
                    cardHolderName: '{{_userFullName}}'
                    expiryMonth: '11'
                    expiryYear: '2222'
                    cardNumber: '4111111111111111'
                    cvv: '111'
                    cardCategory: CreditCard
                    cardType: VISA
                    startYear: '2013'
                    startMonth: '7'
                    nickName: Default Payment Method
                    accountId: '{{defaultAccountId}}'
                  phone: '4155551212'
                  email: '{{_userEmail}}'
                  additionalData:
                    key1: value1
                    key2: value2
              contentMediaType: application/json
            example:
              paymentGatewayId: '{{defaultPaymentGatewayId}}'
              cardPaymentMethod:
                cardHolderName: '{{_userFullName}}'
                expiryMonth: '11'
                expiryYear: '2222'
                cardNumber: '4111111111111111'
                cvv: '111'
                cardCategory: CreditCard
                cardType: VISA
                startYear: '2013'
                startMonth: '7'
                nickName: Default Payment Method
                accountId: '{{defaultAccountId}}'
              phone: '4155551212'
              email: '{{_userEmail}}'
              additionalData:
                key1: value1
                key2: value2
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://services
        variables: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    AdditionalData:
      title: AdditionalData
      required:
      - key1
      - key2
      type: object
      properties:
        key1:
          type: string
          example: example_value
        key2:
          type: string
          example: example_value
      examples:
      - key1: value1
        key2: value2
    Giftcommitment:
      title: Giftcommitment
      required:
      - href
      - id
      type: object
      properties:
        href:
          type: string
          example: example_value
        id:
          type: string
          example: abc123
      examples:
      - href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
        id: <SFDC_GIFT_COMMITMENT_ID>
    Detail3:
      title: Detail3
      required:
      - success
      - links
      type: object
      properties:
        success:
          type: boolean
          example: true
        links:
          $ref: '#/components/schemas/Links3'
      examples:
      - success: true
        links:
          gifttransaction:
            href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
            id: <SFDC_GIFT_TRANSACTION_ID>
    Errors:
      title: Errors
      required:
      - field
      - message
      type: object
      properties:
        field:
          type: string
          example: example_value
        message:
          type: string
          example: example_value
      examples:
      - field: id
        message: <invalid id message>
    Gifttransaction:
      title: Gifttransaction
      required:
      - href
      - id
      type: object
      properties:
        href:
          type: string
          example: example_value
        id:
          type: string
          example: abc123
      examples:
      - href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
        id: <SFDC_GIFT_TRANSACTION_ID>
    PaymentInstrument:
      title: PaymentInstrument
      required:
      - type
      - accountHolderName
      - expiryMonth
      - expiryYear
      - last4
      - cardBrand
      - bankName
      - digitalWalletProvider
      - bankAccountHolderType
      - bankAccountType
      - bankAccountNumber
      - bankCode
      - gatewayName
      - processorName
      - processorPaymentReference
      - gatewayReference
      type: object
      properties:
        type:
          type: string
          example: example_value
        accountHolderName:
          type: string
          example: 42
        expiryMonth:
          type: string
          example: example_value
        expiryYear:
          type: string
          example: example_value
        last4:
          type: string
          example: example_value
        cardBrand:
          type: string
          example: example_value
        bankName:
          type: string
          example: example_value
        digitalWalletProvider:
          type: string
          example: example_value
        bankAccountHolderType:
          type: string
          example: 42
        bankAccountType:
          type: string
          example: 42
        bankAccountNumber:
          type: string
          example: 42
        bankCode:
          type: string
          example: example_value
        gatewayName:
          type: string
          example: example_value
        processorName:
          type: string
          example: example_value
        processorPaymentReference:
          type: string
          example: example_value
        gatewayReference:
          type: string
          example: example_value
      examples:
      - type: credit card
        accountHolderName: test donor
        expiryMonth: '10'
        expiryYear: '2027'
        last4: '4585'
        cardBrand: visa
        bankName: chase
        digitalWalletProvider: apple pay
        bankAccountHolderType: primary
        bankAccountType: checking
        bankAccountNumber: '123456'
        bankCode: HBUK
        gatewayName: stripe
        processorName: test processor
        processorPaymentReference: string
        gatewayReference: string
    Update1:
      title: Update1
      required:
      - giftCommitmentId
      - paymentInstrument
      type: object
      properties:
        giftCommitmentId:
          type: string
          example: '500123'
        paymentInstrument:
          $ref: '#/components/schemas/PaymentInstrument'
      examples:
      - giftCommitmentId: <SFDC_GIFT_COMMITMENT_ID>
        paymentInstrument:
          type: credit card
          accountHolderName: test donor 1
          expiryMonth: '10'
          expiryYear: '2026'
          last4: '4585'
          cardBrand: visa
          bankName: chase
          digitalWalletProvider: apple pay
          bankAccountHolderType: primary
          bankAccountType: checking
          bankAccountNumber: '123456'
          bankCode: HBUK
          gatewayName: stripe
          processorName: classy
          processorPaymentReference: string
          gatewayReference: string
    Status200-UpdateCommitmentRequestValidationFailure1:
      title: Status200-UpdateCommitmentRequestValidationFailure1
      required:
      - successes
      - failures
      - notProcessed
      - details
      type: object
      properties:
        successes:
          type: integer
          contentEncoding: int32
          example: 10
        failures:
          type: integer
          contentEncoding: int32
          example: 10
        notProcessed:
          type: integer
          contentEncoding: int32
          example: 10
        details:
          type: array
          items:
            $ref: '#/components/schemas/Detail14'
          description: ''
          example: []
      examples:
      - successes: 1
        failures: 1
        notProcessed: 0
        details:
        - success: false
          errors:
            field: id
            message: <invalid id message>
        - success: true
          links:
            giftcommitment:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
              id: <SFDC_GIFT_COMMITMENT_ID>
            paymentinstrument:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
              id: <SFDC_PAYMENT_INSTRUMENT_ID>
    Links13:
      title: Links13
      required:
      - giftcommitment
      - paymentinstrument
      type: object
      properties:
        giftcommitment:
          $ref: '#/components/schemas/Giftcommitment'
        paymentinstrument:
          $ref: '#/components/schemas/Paymentinstrument1'
      examples:
      - giftcommitment:
          href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
          id: <SFDC_GIFT_COMMITMENT_ID>
        paymentinstrument:
          href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
          id: <SFDC_PAYMENT_INSTRUMENT_ID>
    Links3:
      title: Links3
      required:
      - gifttransaction
      type: object
      properties:
        gifttransaction:
          $ref: '#/components/schemas/Gifttransaction'
      examples:
      - gifttransaction:
          href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
          id: <SFDC_GIFT_TRANSACTION_ID>
    UpdateCommitmentPaymentsRequest:
      title: UpdateCommitmentPaymentsRequest
      required:
      - updates
      type: object
      properties:
        updates:
          type: array
          items:
            $ref: '#/components/schemas/Update1'
          description: ''
          example: []
      examples:
      - updates:
        - giftCommitmentId: <SFDC_GIFT_COMMITMENT_ID>
          paymentInstrument:
            type: credit card
            accountHolderName: test donor 1
            expiryMonth: '10'
            expiryYear: '2026'
            last4: '4585'
            cardBrand: visa
            bankName: chase
            digitalWalletProvider: apple pay
            bankAccountHolderType: primary
            bankAccountType: checking
            bankAccountNumber: '123456'
            bankCode: HBUK
            gatewayName: stripe
            processorName: classy
            processorPaymentReference: string
            gatewayReference: string
        - giftCommitmentId: <SFDC_GIFT_COMMITMENT_ID>
          paymentInstrument:
            type: credit card
            accountHolderName: test donor 2
            expiryMonth: '10'
            expiryYear: '2026'
            last4: '4585'
            cardBrand: visa
            bankName: chase
            digitalWalletProvider: apple pay
            bankAccountHolderType: primary
            bankAccountType: checking
            bankAccountNumber: '123456'
            bankCode: HBUK
            gatewayName: stripe
            processorName: test processor
            processorPaymentReference: string
            gatewayReference: string
    UpdateGiftTransactionPaymentsRequest:
      title: UpdateGiftTransactionPaymentsRequest
      required:
      - updates
      type: object
      properties:
        updates:
          type: array
          items:
            $ref: '#/components/schemas/Update'
          description: ''
          example: []
      examples:
      - updates:
        - giftTransactionId: <SFDC_GIFT_TRANSACTION_ID>
          transactionStatus: Paid
          processorReference: string
          gatewayReference: string
          lastGatewayResponseCode: invalid_cvc
          lastGatewayErrorMessage: The card’s security code is invalid. Check the card’s security code or use a different card.
          lastGatewayProcessedDateTime: '2023-07-06T21:57:51.000Z'
          processorTransactionFee: 0.5
          gatewayTransactionFee: 0.25
          donorCoverAmount: 10.5
        - giftTransactionId: <SFDC_GIFT_TRANSACTION_ID>
          transactionStatus: Paid
          processorReference: string
          gatewayReference: string
          lastGatewayResponseCode: invalid_cvc
          lastGatewayErrorMessage: The card’s security code is invalid. Check the card’s security code or use a different card.
          lastGatewayProcessedDateTime: '2023-07-06T21:57:51.000Z'
          processorTransactionFee: 1
          gatewayTransactionFee: 0.45
          donorCoverAmount: 20
    CreatePaymentMethodRequest:
      title: CreatePaymentMethodRequest
      required:
      - paymentGatewayId
      - cardPaymentMethod
      - phone
      - email
      - additionalData
      type: object
      properties:
        paymentGatewayId:
          type: string
          example: '500123'
        cardPaymentMethod:
          $ref: '#/components/schemas/CardPaymentMethod'
        phone:
          type: string
          example: example_value
        email:
          type: string
          example: user@example.com
        additionalData:
          $ref: '#/components/schemas/AdditionalData'
      examples:
      - paymentGatewayId: '{{defaultPaymentGatewayId}}'
        cardPaymentMethod:
          cardHolderName: '{{_userFullName}}'
          expiryMonth: '11'
          expiryYear: '2222'
          cardNumber: '4111111111111111'
          cvv: '111'
          cardCategory: CreditCard
          cardType: VISA
          startYear: '2013'
          startMonth: '7'
          nickName: Default Payment Method
          accountId: '{{defaultAccountId}}'
        phone: '4155551212'
        email: '{{_userEmail}}'
        additionalData:
          key1: value1
          key2: value2
    Paymentinstrument1:
      title: Paymentinstrument1
      required:
      - href
      - id
      type: object
      properties:
        href:
          type: string
          example: example_value
        id:
          type: string
          example: abc123
      examples:
      - href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
        id: <SFDC_PAYMENT_INSTRUMENT_ID>
    Detail14:
      title: Detail14
      required:
      - success
      type: object
      properties:
        success:
          type: boolean
          example: true
        errors:
          $ref: '#/components/schemas/Errors'
        links:
          $ref: '#/components/schemas/Links13'
      examples:
      - success: false
        errors:
          field: id
          message: <invalid id message>
    CardPaymentMethod:
      title: CardPaymentMethod
      required:
      - cardHolderName
      - expiryMonth
      - expiryYear
      - cardNumber
      - cvv
      - cardCategory
      - cardType
      - startYear
      - startMonth
      - nickName
      - accountId
      type: object
      properties:
        cardHolderName:
          type: string
          example: example_value
        expiryMonth:
          type: string
          example: example_value
        expiryYear:
          type: string
          example: example_value
        cardNumber:
          type: string
          example: example_value
        cvv:
          type: string
          example: example_value
        cardCategory:
          type: string
          example: example_value
        cardType:
          type: string
          example: example_value
        startYear:
          type: string
          example: example_value
        startMonth:
          type: string
          example: example_value
        nickName:
          type: string
          example: example_value
        accountId:
          type: string
          example: '500123'
      examples:
      - cardHolderName: '{{_userFullName}}'
        expiryMonth: '11'
        expiryYear: '2222'
        cardNumber: '4111111111111111'
        cvv: '111'
        cardCategory: CreditCard
        cardType: VISA
        startYear: '2013'
        startMonth: '7'
        nickName: Default Payment Method
        accountId: '{{defaultAccountId}}'
    Detail13:
      title: Detail13
      required:
      - success
      - links
      type: object
      properties:
        success:
          type: boolean
          example: true
        links:
          $ref: '#/components/schemas/Links13'
      examples:
      - success: true
        links:
          giftcommitment:
            href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
            id: <SFDC_GIFT_COMMITMENT_ID>
          paymentinstrument:
            href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
            id: <SFDC_PAYMENT_INSTRUMENT_ID>
    Update:
      title: Update
      required:
      - giftTransactionId
      - transactionStatus
      - processorReference
      - gatewayReference
      - lastGatewayResponseCode
      - lastGatewayErrorMessage
      - lastGatewayProcessedDateTime
      - processorTransactionFee
      - gatewayTransactionFee
      - donorCoverAmount
      type: object
      properties:
        giftTransactionId:
          type: string
          example: '500123'
        transactionStatus:
          type: string
          example: example_value
        processorReference:
          type: string
          example: example_value
        gatewayReference:
          type: string
          example: example_value
        lastGatewayResponseCode:
          type: string
          example: example_value
        lastGatewayErrorMessage:
          type: string
          example: example_value
        lastGatewayProcessedDateTime:
          type: string
          example: '2026-01-15T10:30:00Z'
        processorTransactionFee:
          type: number
          example: 42.5
        gatewayTransactionFee:
          type: number
          example: 42.5
        donorCoverAmount:
          type: number
          example: 42.5
      examples:
      - giftTransactionId: <SFDC_GIFT_TRANSACTION_ID>
        transactionStatus: Paid
        processorReference: string
        gatewayReference: string
        lastGatewayResponseCode: invalid_cvc
        lastGatewayErrorMessage: The card’s security code is invalid. Check the card’s security code or use a different card.
        lastGatewayProcessedDateTime: '2023-07-06T21:57:51.000Z'
        processorTransactionFee: 0.5
        gatewayTransactionFee: 0.25
        donorCoverAmount: 10.5
    Status201-UpdateCommitmentSuccess:
      title: Status201-UpdateCommitmentSuccess
      required:
      - successes
      - failures
      - notProcessed
      - details
      type: object
      properties:
        successes:
          type: integer
          contentEncoding: int32
          example: 10
        failures:
          type: integer
          contentEncoding: int32
          example: 10
        notProcessed:
          type: integer
          contentEncoding: int32
          example: 10
        details:
          type: array
          items:
            $ref: '#/components/schemas/Detail13'
          description: ''
          example: []
      examples:
      - successes: 2
        failures: 0
        notProcessed: 0
        details:
        - success: true
          links:
            giftcommitment:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
              id: <SFDC_GIFT_COMMITMENT_ID>
            paymentinstrument:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
              id: <SFDC_PAYMENT_INSTRUMENT_ID>
        - success: true
          links:
            giftcommitment:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_COMMITMENT_ID>
              id: <SFDC_GIFT_COMMITMENT_ID>
            paymentinstrument:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_PAYMENT_INSTRUMENT_ID>
              id: <SFDC_PAYMENT_INSTRUMENT_ID>
    Status201-UpdateTransactionPaymentSuccess:
      title: Status201-UpdateTransactionPaymentSuccess
      required:
      - successes
      - failures
      - notProcessed
      - details
      type: object
      properties:
        successes:
          type: integer
          contentEncoding: int32
          example: 10
        failures:
          type: integer
          contentEncoding: int32
          example: 10
        notProcessed:
          type: integer
          contentEncoding: int32
          example: 10
        details:
          type: array
          items:
            $ref: '#/components/schemas/Detail3'
          description: ''
          example: []
      examples:
      - successes: 2
        failures: 0
        notProcessed: 0
        details:
        - success: true
          links:
            gifttransaction:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
              id: <SFDC_GIFT_TRANSACTION_ID>
        - success: true
          links:
            gifttransaction:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
              id: <SFDC_GIFT_TRANSACTION_ID>
    Status201-UpdateTransactionPaymentWithExternalIds1:
      title: Status201-UpdateTransactionPaymentWithExternalIds1
      required:
      - successes
      - failures
      - notProcessed
      - details
      type: object
      properties:
        successes:
          type: integer
          contentEncoding: int32
          example: 10
        failures:
          type: integer
          contentEncoding: int32
          example: 10
        notProcessed:
          type: integer
          contentEncoding: int32
          example: 10
        details:
          type: array
          items:
            $ref: '#/components/schemas/Detail3'
          description: ''
          example: []
      examples:
      - successes: 1
        failures: 0
        notProcessed: 0
        details:
        - success: true
          links:
            gifttransaction:
              href: /services/data/vXX.X/sobjects/sObject/<SFDC_GIFT_TRANSACTION_ID>
              id: <SFDC_GIFT_TRANSACTION_ID>
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: 'OAuth 2.0 Bearer token obtained from the Salesforce OAuth 2.0 token endpoint. Include this token in the Authorization header as "Bearer {access_token}".

        '
