openapi: 3.2.0
info:
  title: Salesforce Record API
  description: 'Find the resources you need to start building. '
  contact: {}
  version: '1.0'
servers:
- url: https://login.salesforce.com
  variables: {}
- url: https://id
  variables: {}
- url: https://services
  variables: {}
- url: '{{url}}{{site}}/services/oauth2'
  variables:
    url:
      default: DefaultParameterValue
    site:
      default: DefaultParameterValue
security:
- oauth2:
  - api
tags:
- name: Record
paths:
  /data/v64.0/ui-api/records/{RECORD_ID}:
    parameters: []
    patch:
      tags:
      - Record
      summary: Salesforce Update a Record
      description: 'Update a record''s data.

        User Interface API enforces Salesforce validation rules. If a validation rule fails, the response is an Error with Output.


        When you make a PATCH request to update a record, make sure that the record hasn’t changed since the user started editing it. To find out whether it’s safe to save a record, pass the If-Modified-Since HTTP header in the request.


        As of API version 43.0, if you pass read-only fields in a request body, the response is an Error with Output.'
      operationId: UpdateaRecord
      parameters:
      - name: RECORD_ID
        in: path
        description: Record ID
        required: true
        schema:
          type: string
        example: '500123'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateaRecordRequest'
              - examples:
                - allowSaveOnDuplicate: false
                  fields:
                    FieldAPIName: FieldValue
              contentMediaType: application/json
            example:
              allowSaveOnDuplicate: false
              fields:
                FieldAPIName: FieldValue
        required: true
      responses:
        '200':
          description: OK
          headers:
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: Wed, 27 Sep 2023 16:04:41 GMT
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: max-age=63072000; includeSubDomains
            X-Content-Type-Options:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: nosniff
            X-XSS-Protection:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: 1; mode=block
            X-Robots-Tag:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: none
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: no-cache,must-revalidate,max-age=0,no-store,private
            ETag:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: '"1be6f040e46732e79a0999d6fea9fe7d"'
            Transfer-Encoding:
              content:
                text/plain:
                  schema:
                    type: string
                    contentMediaType: text/plain
                  example: chunked
          content:
            application/json;charset=UTF-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/UpdateaRecord'
                - examples:
                  - apiName: Account
                    childRelationships: {}
                    eTag: 1be6f040e46732e79a0999d6fea9fe7d
                    fields:
                      AccountNumber:
                        displayValue: null
                        value: null
                      Active__c:
                        displayValue: null
                        value: null
                      AnnualRevenue:
                        displayValue: null
                        value: null
                      BillingCity:
                        displayValue: null
                        value: null
                      BillingCountry:
                        displayValue: null
                        value: null
                      BillingPostalCode:
                        displayValue: null
                        value: null
                      BillingState:
                        displayValue: null
                        value: null
                      BillingStreet:
                        displayValue: null
                        value: null
                      CreatedBy:
                        displayValue: Philippe Ozil
                        value:
                          apiName: User
                          childRelationships: {}
                          eTag: cc07f7ef1b08ddbd75074c69512dd388
                          fields:
                            Id:
                              displayValue: null
                              value: 005B0000003TOI6IAO
                            Name:
                              displayValue: null
                              value: Philippe Ozil
                          id: 005B0000003TOI6IAO
                          lastModifiedById: 005B0000003TOI6IAO
                          lastModifiedDate: '2023-02-02T10:32:12.000Z'
                          recordTypeId: null
                          recordTypeInfo: null
                          systemModstamp: '2023-09-27T15:47:51.000Z'
                          weakEtag: 1695829671000
                      CreatedById:
                        displayValue: null
                        value: 005B0000003TOI6IAO
                      CreatedDate:
                        displayValue: 27/09/2023 18:01
                        value: '2023-09-27T16:01:14.000Z'
                      CustomerPriority__c:
                        displayValue: null
                        value: null
                      Description:
                        displayValue: null
                        value: null
                      Fax:
                        displayValue: null
                        value: null
                      Industry:
                        displayValue: null
                        value: null
                      LastModifiedBy:
                        displayValue: Philippe Ozil
                        value:
                          apiName: User
                          childRelationships: {}
                          eTag: cc07f7ef1b08ddbd75074c69512dd388
                          fields:
                            Id:
                              displayValue: null
                              value: 005B0000003TOI6IAO
                            Name:
                              displayValue: null
                              value: Philippe Ozil
                          id: 005B0000003TOI6IAO
                          lastModifiedById: 005B0000003TOI6IAO
                          lastModifiedDate: '2023-02-02T10:32:12.000Z'
                          recordTypeId: null
                          recordTypeInfo: null
                          systemModstamp: '2023-09-27T15:47:51.000Z'
                          weakEtag: 1695829671000
                      LastModifiedById:
                        displayValue: null
                        value: 005B0000003TOI6IAO
                      LastModifiedDate:
                        displayValue: 27/09/2023 18:04
                        value: '2023-09-27T16:04:41.000Z'
                      Name:
                        displayValue: null
                        value: My Renamed Account
                      NumberOfEmployees:
                        displayValue: null
                        value: null
                      NumberofLocations__c:
                        displayValue: null
                        value: null
                      Owner:
                        displayValue: Philippe Ozil
                        value:
                          apiName: User
                          childRelationships: {}
                          eTag: cc07f7ef1b08ddbd75074c69512dd388
                          fields:
                            Id:
                              displayValue: null
                              value: 005B0000003TOI6IAO
                            Name:
                              displayValue: null
                              value: Philippe Ozil
                          id: 005B0000003TOI6IAO
                          lastModifiedById: 005B0000003TOI6IAO
                          lastModifiedDate: '2023-02-02T10:32:12.000Z'
                          recordTypeId: null
                          recordTypeInfo: null
                          systemModstamp: '2023-09-27T15:47:51.000Z'
                          weakEtag: 1695829671000
                      OwnerId:
                        displayValue: null
                        value: 005B0000003TOI6IAO
                      Ownership:
                        displayValue: null
                        value: null
                      Parent:
                        displayValue: null
                        value: null
                      ParentId:
                        displayValue: null
                        value: null
                      Phone:
                        displayValue: null
                        value: null
                      Rating:
                        displayValue: null
                        value: null
                      SLAExpirationDate__c:
                        displayValue: null
                        value: null
                      SLASerialNumber__c:
                        displayValue: null
                        value: null
                      SLA__c:
                        displayValue: null
                        value: null
                      ShippingCity:
                        displayValue: null
                        value: null
                      ShippingCountry:
                        displayValue: null
                        value: null
                      ShippingPostalCode:
                        displayValue: null
                        value: null
                      ShippingState:
                        displayValue: null
                        value: null
                      ShippingStreet:
                        displayValue: null
                        value: null
                      Sic:
                        displayValue: null
                        value: null
                      Site:
                        displayValue: null
                        value: null
                      TickerSymbol:
                        displayValue: null
                        value: null
                      Type:
                        displayValue: null
                        value: null
                      UpsellOpportunity__c:
                        displayValue: null
                        value: null
                      Website:
                        displayValue: null
                        value: null
                    id: 0011Q00002Z2P5jQAF
                    lastModifiedById: 005B0000003TOI6IAO
                    lastModifiedDate: '2023-09-27T16:04:41.000Z'
                    recordTypeId: 012000000000000AAA
                    recordTypeInfo: null
                    systemModstamp: '2023-09-27T16:04:41.000Z'
                    weakEtag: 1695830681000
                contentMediaType: application/json;charset=UTF-8
              example:
                apiName: Account
                childRelationships: {}
                eTag: 1be6f040e46732e79a0999d6fea9fe7d
                fields:
                  AccountNumber:
                    displayValue: null
                    value: null
                  Active__c:
                    displayValue: null
                    value: null
                  AnnualRevenue:
                    displayValue: null
                    value: null
                  BillingCity:
                    displayValue: null
                    value: null
                  BillingCountry:
                    displayValue: null
                    value: null
                  BillingPostalCode:
                    displayValue: null
                    value: null
                  BillingState:
                    displayValue: null
                    value: null
                  BillingStreet:
                    displayValue: null
                    value: null
                  CreatedBy:
                    displayValue: Philippe Ozil
                    value:
                      apiName: User
                      childRelationships: {}
                      eTag: cc07f7ef1b08ddbd75074c69512dd388
                      fields:
                        Id:
                          displayValue: null
                          value: 005B0000003TOI6IAO
                        Name:
                          displayValue: null
                          value: Philippe Ozil
                      id: 005B0000003TOI6IAO
                      lastModifiedById: 005B0000003TOI6IAO
                      lastModifiedDate: '2023-02-02T10:32:12.000Z'
                      recordTypeId: null
                      recordTypeInfo: null
                      systemModstamp: '2023-09-27T15:47:51.000Z'
                      weakEtag: 1695829671000
                  CreatedById:
                    displayValue: null
                    value: 005B0000003TOI6IAO
                  CreatedDate:
                    displayValue: 27/09/2023 18:01
                    value: '2023-09-27T16:01:14.000Z'
                  CustomerPriority__c:
                    displayValue: null
                    value: null
                  Description:
                    displayValue: null
                    value: null
                  Fax:
                    displayValue: null
                    value: null
                  Industry:
                    displayValue: null
                    value: null
                  LastModifiedBy:
                    displayValue: Philippe Ozil
                    value:
                      apiName: User
                      childRelationships: {}
                      eTag: cc07f7ef1b08ddbd75074c69512dd388
                      fields:
                        Id:
                          displayValue: null
                          value: 005B0000003TOI6IAO
                        Name:
                          displayValue: null
                          value: Philippe Ozil
                      id: 005B0000003TOI6IAO
                      lastModifiedById: 005B0000003TOI6IAO
                      lastModifiedDate: '2023-02-02T10:32:12.000Z'
                      recordTypeId: null
                      recordTypeInfo: null
                      systemModstamp: '2023-09-27T15:47:51.000Z'
                      weakEtag: 1695829671000
                  LastModifiedById:
                    displayValue: null
                    value: 005B0000003TOI6IAO
                  LastModifiedDate:
                    displayValue: 27/09/2023 18:04
                    value: '2023-09-27T16:04:41.000Z'
                  Name:
                    displayValue: null
                    value: My Renamed Account
                  NumberOfEmployees:
                    displayValue: null
                    value: null
                  NumberofLocations__c:
                    displayValue: null
                    value: null
                  Owner:
                    displayValue: Philippe Ozil
                    value:
                      apiName: User
                      childRelationships: {}
                      eTag: cc07f7ef1b08ddbd75074c69512dd388
                      fields:
                        Id:
                          displayValue: null
                          value: 005B0000003TOI6IAO
                        Name:
                          displayValue: null
                          value: Philippe Ozil
                      id: 005B0000003TOI6IAO
                      lastModifiedById: 005B0000003TOI6IAO
                      lastModifiedDate: '2023-02-02T10:32:12.000Z'
                      recordTypeId: null
                      recordTypeInfo: null
                      systemModstamp: '2023-09-27T15:47:51.000Z'
                      weakEtag: 1695829671000
                  OwnerId:
                    displayValue: null
                    value: 005B0000003TOI6IAO
                  Ownership:
                    displayValue: null
                    value: null
                  Parent:
                    displayValue: null
                    value: null
                  ParentId:
                    displayValue: null
                    value: null
                  Phone:
                    displayValue: null
                    value: null
                  Rating:
                    displayValue: null
                    value: null
                  SLAExpirationDate__c:
                    displayValue: null
                    value: null
                  SLASerialNumber__c:
                    displayValue: null
                    value: null
                  SLA__c:
                    displayValue: null
                    value: null
                  ShippingCity:
                    displayValue: null
                    value: null
                  ShippingCountry:
                    displayValue: null
                    value: null
                  ShippingPostalCode:
                    displayValue: null
                    value: null
                  ShippingState:
                    displayValue: null
                    value: null
                  ShippingStreet:
                    displayValue: null
                    value: null
                  Sic:
                    displayValue: null
                    value: null
                  Site:
                    displayValue: null
                    value: null
                  TickerSymbol:
                    displayValue: null
                    value: null
                  Type:
                    displayValue: null
                    value: null
                  UpsellOpportunity__c:
                    displayValue: null
                    value: null
                  Website:
                    displayValue: null
                    value: null
                id: 0011Q00002Z2P5jQAF
                lastModifiedById: 005B0000003TOI6IAO
                lastModifiedDate: '2023-09-27T16:04:41.000Z'
                recordTypeId: 012000000000000AAA
                recordTypeInfo: null
                systemModstamp: '2023-09-27T16:04:41.000Z'
                weakEtag: 1695830681000
      deprecated: false
      servers:
      - url: https://services
        variables: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    Id8:
      title: Id8
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type: string
          example: example_value
      examples:
      - displayValue: null
        value: 005B0000003TOI6IAO
    Value:
      title: Value
      required:
      - apiName
      - childRelationships
      - eTag
      - fields
      - id
      - lastModifiedById
      - lastModifiedDate
      - recordTypeId
      - recordTypeInfo
      - systemModstamp
      - weakEtag
      type: object
      properties:
        apiName:
          type: string
          example: example_value
        childRelationships:
          type: object
          example: example_value
        eTag:
          type: string
          example: example_value
        fields:
          $ref: '#/components/schemas/Fields8'
        id:
          type: string
          example: abc123
        lastModifiedById:
          type: string
          example: '500123'
        lastModifiedDate:
          type: string
          example: example_value
        recordTypeId:
          type:
          - string
          - 'null'
          example: '500123'
        recordTypeInfo:
          type:
          - string
          - 'null'
          example: example_value
        systemModstamp:
          type: string
          example: example_value
        weakEtag:
          type: integer
          contentEncoding: int64
          example: 10
      examples:
      - apiName: User
        childRelationships: {}
        eTag: cc07f7ef1b08ddbd75074c69512dd388
        fields:
          Id:
            displayValue: null
            value: 005B0000003TOI6IAO
          Name:
            displayValue: null
            value: Philippe Ozil
        id: 005B0000003TOI6IAO
        lastModifiedById: 005B0000003TOI6IAO
        lastModifiedDate: '2023-02-02T10:32:12.000Z'
        recordTypeId: null
        recordTypeInfo: null
        systemModstamp: '2023-09-27T15:47:51.000Z'
        weakEtag: 1695829671000
    Name21:
      title: Name21
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type: string
          example: example_value
      examples:
      - displayValue: null
        value: Philippe Ozil
    Type13:
      title: Type13
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    SLAExpirationDateC2:
      title: SLAExpirationDateC2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    LastModifiedDate5:
      title: LastModifiedDate5
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type: string
          example: example_value
        value:
          type: string
          example: example_value
      examples:
      - displayValue: 27/09/2023 17:47
        value: '2023-09-27T15:47:56.000Z'
    Industry3:
      title: Industry3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    UpdateaRecordRequest:
      title: UpdateaRecordRequest
      required:
      - allowSaveOnDuplicate
      - fields
      type: object
      properties:
        allowSaveOnDuplicate:
          type: boolean
          example: true
        fields:
          $ref: '#/components/schemas/Fields20'
      examples:
      - allowSaveOnDuplicate: false
        fields:
          FieldAPIName: FieldValue
    SLAC2:
      title: SLAC2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    ParentId2:
      title: ParentId2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    ShippingStreet2:
      title: ShippingStreet2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Owner6:
      title: Owner6
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type: string
          example: example_value
        value:
          $ref: '#/components/schemas/Value'
      examples:
      - displayValue: Philippe Ozil
        value:
          apiName: User
          childRelationships: {}
          eTag: cc07f7ef1b08ddbd75074c69512dd388
          fields:
            Id:
              displayValue: null
              value: 005B0000003TOI6IAO
            Name:
              displayValue: null
              value: Philippe Ozil
          id: 005B0000003TOI6IAO
          lastModifiedById: 005B0000003TOI6IAO
          lastModifiedDate: '2023-02-02T10:32:12.000Z'
          recordTypeId: null
          recordTypeInfo: null
          systemModstamp: '2023-09-27T15:47:51.000Z'
          weakEtag: 1695829671000
    Site2:
      title: Site2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Phone9:
      title: Phone9
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Fields21:
      title: Fields21
      required:
      - AccountNumber
      - Active__c
      - AnnualRevenue
      - BillingCity
      - BillingCountry
      - BillingPostalCode
      - BillingState
      - BillingStreet
      - CreatedBy
      - CreatedById
      - CreatedDate
      - CustomerPriority__c
      - Description
      - Fax
      - Industry
      - LastModifiedBy
      - LastModifiedById
      - LastModifiedDate
      - Name
      - NumberOfEmployees
      - NumberofLocations__c
      - Owner
      - OwnerId
      - Ownership
      - Parent
      - ParentId
      - Phone
      - Rating
      - SLAExpirationDate__c
      - SLASerialNumber__c
      - SLA__c
      - ShippingCity
      - ShippingCountry
      - ShippingPostalCode
      - ShippingState
      - ShippingStreet
      - Sic
      - Site
      - TickerSymbol
      - Type
      - UpsellOpportunity__c
      - Website
      type: object
      properties:
        AccountNumber:
          $ref: '#/components/schemas/AccountNumber2'
        Active__c:
          $ref: '#/components/schemas/ActiveC2'
        AnnualRevenue:
          $ref: '#/components/schemas/AnnualRevenue3'
        BillingCity:
          $ref: '#/components/schemas/BillingCity3'
        BillingCountry:
          $ref: '#/components/schemas/BillingCountry3'
        BillingPostalCode:
          $ref: '#/components/schemas/BillingPostalCode3'
        BillingState:
          $ref: '#/components/schemas/BillingState3'
        BillingStreet:
          $ref: '#/components/schemas/BillingStreet3'
        CreatedBy:
          $ref: '#/components/schemas/CreatedBy3'
        CreatedById:
          $ref: '#/components/schemas/CreatedById5'
        CreatedDate:
          $ref: '#/components/schemas/CreatedDate5'
        CustomerPriority__c:
          $ref: '#/components/schemas/CustomerPriorityC2'
        Description:
          $ref: '#/components/schemas/Description6'
        Fax:
          $ref: '#/components/schemas/Fax5'
        Industry:
          $ref: '#/components/schemas/Industry3'
        LastModifiedBy:
          $ref: '#/components/schemas/LastModifiedBy3'
        LastModifiedById:
          $ref: '#/components/schemas/LastModifiedById5'
        LastModifiedDate:
          $ref: '#/components/schemas/LastModifiedDate5'
        Name:
          $ref: '#/components/schemas/Name21'
        NumberOfEmployees:
          $ref: '#/components/schemas/NumberOfEmployees2'
        NumberofLocations__c:
          $ref: '#/components/schemas/NumberofLocationsC5'
        Owner:
          $ref: '#/components/schemas/Owner6'
        OwnerId:
          $ref: '#/components/schemas/OwnerId4'
        Ownership:
          $ref: '#/components/schemas/Ownership2'
        Parent:
          $ref: '#/components/schemas/Parent7'
        ParentId:
          $ref: '#/components/schemas/ParentId2'
        Phone:
          $ref: '#/components/schemas/Phone9'
        Rating:
          $ref: '#/components/schemas/Rating3'
        SLAExpirationDate__c:
          $ref: '#/components/schemas/SLAExpirationDateC2'
        SLASerialNumber__c:
          $ref: '#/components/schemas/SLASerialNumberC2'
        SLA__c:
          $ref: '#/components/schemas/SLAC2'
        ShippingCity:
          $ref: '#/components/schemas/ShippingCity2'
        ShippingCountry:
          $ref: '#/components/schemas/ShippingCountry2'
        ShippingPostalCode:
          $ref: '#/components/schemas/ShippingPostalCode2'
        ShippingState:
          $ref: '#/components/schemas/ShippingState2'
        ShippingStreet:
          $ref: '#/components/schemas/ShippingStreet2'
        Sic:
          $ref: '#/components/schemas/Sic2'
        Site:
          $ref: '#/components/schemas/Site2'
        TickerSymbol:
          $ref: '#/components/schemas/TickerSymbol2'
        Type:
          $ref: '#/components/schemas/Type13'
        UpsellOpportunity__c:
          $ref: '#/components/schemas/UpsellOpportunityC2'
        Website:
          $ref: '#/components/schemas/Website2'
      examples:
      - AccountNumber:
          displayValue: null
          value: null
        Active__c:
          displayValue: null
          value: null
        AnnualRevenue:
          displayValue: null
          value: null
        BillingCity:
          displayValue: null
          value: null
        BillingCountry:
          displayValue: null
          value: null
        BillingPostalCode:
          displayValue: null
          value: null
        BillingState:
          displayValue: null
          value: null
        BillingStreet:
          displayValue: null
          value: null
        CreatedBy:
          displayValue: Philippe Ozil
          value:
            apiName: User
            childRelationships: {}
            eTag: cc07f7ef1b08ddbd75074c69512dd388
            fields:
              Id:
                displayValue: null
                value: 005B0000003TOI6IAO
              Name:
                displayValue: null
                value: Philippe Ozil
            id: 005B0000003TOI6IAO
            lastModifiedById: 005B0000003TOI6IAO
            lastModifiedDate: '2023-02-02T10:32:12.000Z'
            recordTypeId: null
            recordTypeInfo: null
            systemModstamp: '2023-09-27T15:47:51.000Z'
            weakEtag: 1695829671000
        CreatedById:
          displayValue: null
          value: 005B0000003TOI6IAO
        CreatedDate:
          displayValue: 27/09/2023 18:01
          value: '2023-09-27T16:01:14.000Z'
        CustomerPriority__c:
          displayValue: null
          value: null
        Description:
          displayValue: null
          value: null
        Fax:
          displayValue: null
          value: null
        Industry:
          displayValue: null
          value: null
        LastModifiedBy:
          displayValue: Philippe Ozil
          value:
            apiName: User
            childRelationships: {}
            eTag: cc07f7ef1b08ddbd75074c69512dd388
            fields:
              Id:
                displayValue: null
                value: 005B0000003TOI6IAO
              Name:
                displayValue: null
                value: Philippe Ozil
            id: 005B0000003TOI6IAO
            lastModifiedById: 005B0000003TOI6IAO
            lastModifiedDate: '2023-02-02T10:32:12.000Z'
            recordTypeId: null
            recordTypeInfo: null
            systemModstamp: '2023-09-27T15:47:51.000Z'
            weakEtag: 1695829671000
        LastModifiedById:
          displayValue: null
          value: 005B0000003TOI6IAO
        LastModifiedDate:
          displayValue: 27/09/2023 18:01
          value: '2023-09-27T16:01:14.000Z'
        Name:
          displayValue: null
          value: My New Account
        NumberOfEmployees:
          displayValue: null
          value: null
        NumberofLocations__c:
          displayValue: null
          value: null
        Owner:
          displayValue: Philippe Ozil
          value:
            apiName: User
            childRelationships: {}
            eTag: cc07f7ef1b08ddbd75074c69512dd388
            fields:
              Id:
                displayValue: null
                value: 005B0000003TOI6IAO
              Name:
                displayValue: null
                value: Philippe Ozil
            id: 005B0000003TOI6IAO
            lastModifiedById: 005B0000003TOI6IAO
            lastModifiedDate: '2023-02-02T10:32:12.000Z'
            recordTypeId: null
            recordTypeInfo: null
            systemModstamp: '2023-09-27T15:47:51.000Z'
            weakEtag: 1695829671000
        OwnerId:
          displayValue: null
          value: 005B0000003TOI6IAO
        Ownership:
          displayValue: null
          value: null
        Parent:
          displayValue: null
          value: null
        ParentId:
          displayValue: null
          value: null
        Phone:
          displayValue: null
          value: null
        Rating:
          displayValue: null
          value: null
        SLAExpirationDate__c:
          displayValue: null
          value: null
        SLASerialNumber__c:
          displayValue: null
          value: null
        SLA__c:
          displayValue: null
          value: null
        ShippingCity:
          displayValue: null
          value: null
        ShippingCountry:
          displayValue: null
          value: null
        ShippingPostalCode:
          displayValue: null
          value: null
        ShippingState:
          displayValue: null
          value: null
        ShippingStreet:
          displayValue: null
          value: null
        Sic:
          displayValue: null
          value: null
        Site:
          displayValue: null
          value: null
        TickerSymbol:
          displayValue: null
          value: null
        Type:
          displayValue: null
          value: null
        UpsellOpportunity__c:
          displayValue: null
          value: null
        Website:
          displayValue: null
          value: null
    CreatedById5:
      title: CreatedById5
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type: string
          example: example_value
      examples:
      - displayValue: null
        value: 005B0000003TOI6IAO
    TickerSymbol2:
      title: TickerSymbol2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Sic2:
      title: Sic2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    ShippingCountry2:
      title: ShippingCountry2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    ActiveC2:
      title: ActiveC2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    AnnualRevenue3:
      title: AnnualRevenue3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    NumberofLocationsC5:
      title: NumberofLocationsC5
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Fax5:
      title: Fax5
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    CreatedDate5:
      title: CreatedDate5
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type: string
          example: example_value
        value:
          type: string
          example: example_value
      examples:
      - displayValue: 18/08/2017 16:46
        value: '2017-08-18T14:46:22.000Z'
    LastModifiedById5:
      title: LastModifiedById5
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type: string
          example: example_value
      examples:
      - displayValue: null
        value: 005B0000003TOI6IAO
    BillingPostalCode3:
      title: BillingPostalCode3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Parent7:
      title: Parent7
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Fields20:
      title: Fields20
      required:
      - FieldAPIName
      type: object
      properties:
        FieldAPIName:
          type: string
          example: example_value
      examples:
      - FieldAPIName: FieldValue
    BillingCountry3:
      title: BillingCountry3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    LastModifiedBy3:
      title: LastModifiedBy3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type: string
          example: example_value
        value:
          $ref: '#/components/schemas/Value'
      examples:
      - displayValue: Philippe Ozil
        value:
          apiName: User
          childRelationships: {}
          eTag: cc07f7ef1b08ddbd75074c69512dd388
          fields:
            Id:
              displayValue: null
              value: 005B0000003TOI6IAO
            Name:
              displayValue: null
              value: Philippe Ozil
          id: 005B0000003TOI6IAO
          lastModifiedById: 005B0000003TOI6IAO
          lastModifiedDate: '2023-02-02T10:32:12.000Z'
          recordTypeId: null
          recordTypeInfo: null
          systemModstamp: '2023-09-27T15:47:51.000Z'
          weakEtag: 1695829671000
    UpsellOpportunityC2:
      title: UpsellOpportunityC2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Website2:
      title: Website2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    CustomerPriorityC2:
      title: CustomerPriorityC2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Ownership2:
      title: Ownership2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    AccountNumber2:
      title: AccountNumber2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    ShippingState2:
      title: ShippingState2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Rating3:
      title: Rating3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    Description6:
      title: Description6
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    UpdateaRecord:
      title: UpdateaRecord
      required:
      - apiName
      - childRelationships
      - eTag
      - fields
      - id
      - lastModifiedById
      - lastModifiedDate
      - recordTypeId
      - recordTypeInfo
      - systemModstamp
      - weakEtag
      type: object
      properties:
        apiName:
          type: string
          example: example_value
        childRelationships:
          type: object
          example: example_value
        eTag:
          type: string
          example: example_value
        fields:
          $ref: '#/components/schemas/Fields21'
        id:
          type: string
          example: abc123
        lastModifiedById:
          type: string
          example: '500123'
        lastModifiedDate:
          type: string
          example: example_value
        recordTypeId:
          type: string
          example: '500123'
        recordTypeInfo:
          type:
          - string
          - 'null'
          example: example_value
        systemModstamp:
          type: string
          example: example_value
        weakEtag:
          type: integer
          contentEncoding: int64
          example: 10
      examples:
      - apiName: Account
        childRelationships: {}
        eTag: 1be6f040e46732e79a0999d6fea9fe7d
        fields:
          AccountNumber:
            displayValue: null
            value: null
          Active__c:
            displayValue: null
            value: null
          AnnualRevenue:
            displayValue: null
            value: null
          BillingCity:
            displayValue: null
            value: null
          BillingCountry:
            displayValue: null
            value: null
          BillingPostalCode:
            displayValue: null
            value: null
          BillingState:
            displayValue: null
            value: null
          BillingStreet:
            displayValue: null
            value: null
          CreatedBy:
            displayValue: Philippe Ozil
            value:
              apiName: User
              childRelationships: {}
              eTag: cc07f7ef1b08ddbd75074c69512dd388
              fields:
                Id:
                  displayValue: null
                  value: 005B0000003TOI6IAO
                Name:
                  displayValue: null
                  value: Philippe Ozil
              id: 005B0000003TOI6IAO
              lastModifiedById: 005B0000003TOI6IAO
              lastModifiedDate: '2023-02-02T10:32:12.000Z'
              recordTypeId: null
              recordTypeInfo: null
              systemModstamp: '2023-09-27T15:47:51.000Z'
              weakEtag: 1695829671000
          CreatedById:
            displayValue: null
            value: 005B0000003TOI6IAO
          CreatedDate:
            displayValue: 27/09/2023 18:01
            value: '2023-09-27T16:01:14.000Z'
          CustomerPriority__c:
            displayValue: null
            value: null
          Description:
            displayValue: null
            value: null
          Fax:
            displayValue: null
            value: null
          Industry:
            displayValue: null
            value: null
          LastModifiedBy:
            displayValue: Philippe Ozil
            value:
              apiName: User
              childRelationships: {}
              eTag: cc07f7ef1b08ddbd75074c69512dd388
              fields:
                Id:
                  displayValue: null
                  value: 005B0000003TOI6IAO
                Name:
                  displayValue: null
                  value: Philippe Ozil
              id: 005B0000003TOI6IAO
              lastModifiedById: 005B0000003TOI6IAO
              lastModifiedDate: '2023-02-02T10:32:12.000Z'
              recordTypeId: null
              recordTypeInfo: null
              systemModstamp: '2023-09-27T15:47:51.000Z'
              weakEtag: 1695829671000
          LastModifiedById:
            displayValue: null
            value: 005B0000003TOI6IAO
          LastModifiedDate:
            displayValue: 27/09/2023 18:04
            value: '2023-09-27T16:04:41.000Z'
          Name:
            displayValue: null
            value: My Renamed Account
          NumberOfEmployees:
            displayValue: null
            value: null
          NumberofLocations__c:
            displayValue: null
            value: null
          Owner:
            displayValue: Philippe Ozil
            value:
              apiName: User
              childRelationships: {}
              eTag: cc07f7ef1b08ddbd75074c69512dd388
              fields:
                Id:
                  displayValue: null
                  value: 005B0000003TOI6IAO
                Name:
                  displayValue: null
                  value: Philippe Ozil
              id: 005B0000003TOI6IAO
              lastModifiedById: 005B0000003TOI6IAO
              lastModifiedDate: '2023-02-02T10:32:12.000Z'
              recordTypeId: null
              recordTypeInfo: null
              systemModstamp: '2023-09-27T15:47:51.000Z'
              weakEtag: 1695829671000
          OwnerId:
            displayValue: null
            value: 005B0000003TOI6IAO
          Ownership:
            displayValue: null
            value: null
          Parent:
            displayValue: null
            value: null
          ParentId:
            displayValue: null
            value: null
          Phone:
            displayValue: null
            value: null
          Rating:
            displayValue: null
            value: null
          SLAExpirationDate__c:
            displayValue: null
            value: null
          SLASerialNumber__c:
            displayValue: null
            value: null
          SLA__c:
            displayValue: null
            value: null
          ShippingCity:
            displayValue: null
            value: null
          ShippingCountry:
            displayValue: null
            value: null
          ShippingPostalCode:
            displayValue: null
            value: null
          ShippingState:
            displayValue: null
            value: null
          ShippingStreet:
            displayValue: null
            value: null
          Sic:
            displayValue: null
            value: null
          Site:
            displayValue: null
            value: null
          TickerSymbol:
            displayValue: null
            value: null
          Type:
            displayValue: null
            value: null
          UpsellOpportunity__c:
            displayValue: null
            value: null
          Website:
            displayValue: null
            value: null
        id: 0011Q00002Z2P5jQAF
        lastModifiedById: 005B0000003TOI6IAO
        lastModifiedDate: '2023-09-27T16:04:41.000Z'
        recordTypeId: 012000000000000AAA
        recordTypeInfo: null
        systemModstamp: '2023-09-27T16:04:41.000Z'
        weakEtag: 1695830681000
    SLASerialNumberC2:
      title: SLASerialNumberC2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    NumberOfEmployees2:
      title: NumberOfEmployees2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    ShippingCity2:
      title: ShippingCity2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    ShippingPostalCode2:
      title: ShippingPostalCode2
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    BillingState3:
      title: BillingState3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    BillingStreet3:
      title: BillingStreet3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
    OwnerId4:
      title: OwnerId4
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type: string
          example: example_value
      examples:
      - displayValue: null
        value: 005B0000003TOI6IAO
    CreatedBy3:
      title: CreatedBy3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type: string
          example: example_value
        value:
          $ref: '#/components/schemas/Value'
      examples:
      - displayValue: Philippe Ozil
        value:
          apiName: User
          childRelationships: {}
          eTag: cc07f7ef1b08ddbd75074c69512dd388
          fields:
            Id:
              displayValue: null
              value: 005B0000003TOI6IAO
            Name:
              displayValue: null
              value: Philippe Ozil
          id: 005B0000003TOI6IAO
          lastModifiedById: 005B0000003TOI6IAO
          lastModifiedDate: '2023-02-02T10:32:12.000Z'
          recordTypeId: null
          recordTypeInfo: null
          systemModstamp: '2023-09-27T15:47:51.000Z'
          weakEtag: 1695829671000
    Fields8:
      title: Fields8
      required:
      - Id
      - Name
      type: object
      properties:
        Id:
          $ref: '#/components/schemas/Id8'
        Name:
          $ref: '#/components/schemas/Name21'
      examples:
      - Id:
          displayValue: null
          value: 005B0000003TOI6IAO
        Name:
          displayValue: null
          value: Philippe Ozil
    BillingCity3:
      title: BillingCity3
      required:
      - displayValue
      - value
      type: object
      properties:
        displayValue:
          type:
          - string
          - 'null'
          example: example_value
        value:
          type:
          - string
          - 'null'
          example: example_value
      examples:
      - displayValue: null
        value: null
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: '{DefaultParameterValue}{DefaultParameterValue}/services/oauth2/authorize'
          scopes:
            api: ''
